version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: development
    networks:
      - tic-tac-toe-net

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    environment:
      - REACT_APP_BACKEND_URL=http://backend:5000 # ← 여기 수정
    depends_on:
      - backend
    networks:
      - tic-tac-toe-net

networks:
  tic-tac-toe-net:
    driver: bridge
