version: "3"
services:
    backend:
        build:
            context: ..
            dockerfile: docker/Dockerfile.backend
        ports:
            - "3000:3000"
        depends_on:
            - mongodb
        environment:
            - MONGO_URI=mongodb://mongodb:27017/webgame

    frontend:
        build:
            context: ..
            dockerfile: docker/Dockerfile.frontend
        ports:
            - "80:80"

    mongodb:
        image: mongo:4.4
        ports:
            - "27017:27017"
        volumes:
            - mongo-data:/data/db

volumes:
    mongo-data:
